#!/bin/sh

grep Objective serial/npcdensls_serial.Rout n_2/npcdensls_npRmpi.Rout
grep Objective serial/npcdensml_serial.Rout n_2/npcdensml_npRmpi.Rout
grep Objective serial/npcdistccdf_serial.Rout n_2/npcdistccdf_npRmpi.Rout
grep Objective serial/npcmstest_serial.Rout n_2/npcmstest_npRmpi.Rout
grep Objective serial/npconmode_serial.Rout n_2/npconmode_npRmpi.Rout
grep Objective serial/npdeneqtest_serial.Rout n_2/npdeneqtest_npRmpi.Rout
grep Objective serial/npdeptest_serial.Rout n_2/npdeptest_npRmpi.Rout
grep Objective serial/npindexich_serial.Rout n_2/npindexich_npRmpi.Rout
grep Objective serial/npindexks_serial.Rout n_2/npindexks_npRmpi.Rout
grep Objective serial/npqreg_serial.Rout n_2/npqreg_npRmpi.Rout
grep Objective serial/npreglcaic_serial.Rout n_2/npreglcaic_npRmpi.Rout
grep Objective serial/npreglcls_serial.Rout n_2/npreglcls_npRmpi.Rout
grep Objective serial/npregllaic_serial.Rout n_2/npregllaic_npRmpi.Rout
grep Objective serial/npregllls_serial.Rout n_2/npregllls_npRmpi.Rout
grep Objective serial/npscoef_serial.Rout n_2/npscoef_npRmpi.Rout
grep Objective serial/npsdeptest_serial.Rout n_2/npsdeptest_npRmpi.Rout
grep Objective serial/npsigtest_serial.Rout n_2/npsigtest_npRmpi.Rout
grep Objective serial/npsymtest_serial.Rout n_2/npsymtest_npRmpi.Rout
grep Objective serial/npudensls_serial.Rout n_2/npudensls_npRmpi.Rout
grep Objective serial/npudensml_serial.Rout n_2/npudensml_npRmpi.Rout
grep Objective serial/npunitest_serial.Rout n_2/npunitest_npRmpi.Rout
